# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parduota' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parduota
    pod 'SVProgressHUD', '~> 2.0'
    pod 'R.swift', '~> 3.0'
    pod 'SwiftHEXColors', '~> 1.0'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'ObjectMapper', '~> 2.2'
end
